title:            Coding Star
description:      "An Engineer's Diary"
logo:             logo.png
disqus_shortname: daviddao
share:            true
readtime:			    true
wpm:				      200
theme:				    
header_bg:        
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url: http://iriscshih.github.io/coding-star              

# Owner/author information (EDIT)
owner:
  name:           David Dao
  avatar:         daviddao.jpg
  email:          david.dao@tum.de
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Researcher in machine learning and data science, co-founder of Forschungspreisende and passport stamp collector. I am fascinated with topics like big data, fast algorithms and artificial intelligence.
  # Social networking links used in footer. Update and remove as you like.
  twitter:        david_dao_
  facebook:       profile.daviddao
  github:         daviddao  
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   

owner2:
  name:           Iris Shih
  avatar:         irisshih.jpg
  email:          iris.cshih@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Master of Informatics student in Technical University Munich, major in computer vision and biomedical computing. I am facinated in data visualization, imaging processing and machine learning. 
  # Social networking links used in footer. Update and remove as you like.
  twitter:        iriscshih
  facebook:       iriscShih
  github:         IriscShih  
  # For Google Authorship https://plus.google.com/authorship
  google_plus:  

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Featured Posts
    url: /featured
  - title: Categories
    url: /categories
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  siteurl: ''
  relativeLinks: ''
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "beadline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Physics"
              value: physics
            - name: "Psychology"
              value: psychology
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false
      - name: "chart"
        field:
          element: "checkbox"
          label: "Chart?"
          value: false
      - name: "charttype"
        field:
          element: "select"
          label: "Select Chart Type"
          placeholder: "Choose Type"
          value:
          options:
            - name: "None"
              value: 
            - name: "pie"
              value: pie
            - name: "serial"
              value: serial


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
